apiVersion: 1

datasources:
  - name: Weather Data
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    uid: weather_elastic_01
    
    database: "weather-data-*"
    
    isDefault: true
    
    jsonData:
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
      includeFrozen: false
      esVersion: "8.0.0"
